Selected Key performance Indicators are:

- Claim Frequency (proportion of policies with at least one claim)
- Claim Severity (the average amount of a claim, given a claim occurred)
- Margin (TotalPremium - TotalClaims)

Null Hypotheses to accept or reject are:

- H₀:There are no risk differences across provinces
- H₀:There are no risk differences between zip codes
- H₀:There are no significant margin (profit) difference between zip codes
- H₀:There are not significant risk difference between Women and Men

Calculating Claim Frequency (proportion of policies with at least one claim), Claim Severity  (the average amount of a claim, given a claim occurred)., and Margin (TotalPremium - TotalClaims)

In [1]:
# Import Cleaned Dataset
import pandas as pd


dataset_path = '..\data\processed\CleanedMachineLearningRating_v3.csv'
df = pd.read_csv(dataset_path)

C:\Users\redie\AppData\Local\Temp\ipykernel_3044\4219075839.py:6: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(dataset_path)

In [2]:
df.head()

,Unnamed: 0,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,LegalType,Title,Language,AccountType,MaritalStatus,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,0,145249,12827,2015-03-01 00:00:00,True,Close Corporation,Mr,English,Current account,Not specified,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,1,145249,12827,2015-05-01 00:00:00,True,Close Corporation,Mr,English,Current account,Not specified,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,2,145249,12827,2015-07-01 00:00:00,True,Close Corporation,Mr,English,Current account,Not specified,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,3,145255,12827,2015-05-01 00:00:00,True,Close Corporation,Mr,English,Current account,Not specified,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,4,145255,12827,2015-07-01 00:00:00,True,Close Corporation,Mr,English,Current account,Not specified,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [3]:
# Margin
df['Margin'] = df['TotalPremium'] - df['TotalClaims']

In [5]:
# Claim Frequency (Proportion of policies with at least one claim)
df['HasClaim'] = (df['TotalClaims'] > 0).astype(int)

In [ ]:
# Claim Severity  (the average amount of a claim, given a claim occurred)
# Depends on TotalClaims

In [6]:
df.head()

,Unnamed: 0,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,LegalType,Title,Language,AccountType,MaritalStatus,...,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims,Margin,HasClaim
0,0,145249,12827,2015-03-01 00:00:00,True,Close Corporation,Mr,English,Current account,Not specified,...,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0,21.929825,0
1,1,145249,12827,2015-05-01 00:00:00,True,Close Corporation,Mr,English,Current account,Not specified,...,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0,21.929825,0
2,2,145249,12827,2015-07-01 00:00:00,True,Close Corporation,Mr,English,Current account,Not specified,...,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0,0.000000,0
3,3,145255,12827,2015-05-01 00:00:00,True,Close Corporation,Mr,English,Current account,Not specified,...,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0,512.848070,0
4,4,145255,12827,2015-07-01 00:00:00,True,Close Corporation,Mr,English,Current account,Not specified,...,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0,0.000000,0

In [8]:
df_filtered = df[df['HasClaim'] == 1]

In [9]:
df_filtered.head()

,Unnamed: 0,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,LegalType,Title,Language,AccountType,MaritalStatus,...,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims,Margin,HasClaim
203,203,46222,4044,2014-10-01 00:00:00,False,Close Corporation,Mr,English,Current account,Not specified,...,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,2294.096491,-2294.096491,1
284,284,82062,7174,2015-03-01 00:00:00,True,Close Corporation,Mr,English,Current account,Not specified,...,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,2040.473684,-2018.543860,1
1281,1560,119591,8672,2015-04-01 00:00:00,False,Close Corporation,Mr,English,Current account,Not specified,...,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,1213.889211,46492.211754,-45278.322544,1
1500,1779,50193,283,2014-10-01 00:00:00,False,Close Corporation,Mr,English,Current account,Not specified,...,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,645.017456,26516.859649,-25871.842193,1
1664,1943,119582,8672,2015-04-01 00:00:00,False,Close Corporation,Mr,English,Current account,Not specified,...,Income Protector,Income Protector,Optional Extended Covers,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,74.561404,6140.350877,-6065.789474,1

### Anova-Tests

#### H₀:There are no risk differences across provinces

In [10]:
# Get list of provinces
print(df.groupby('Province')['TotalClaims'].mean().round(2))

Province
Eastern Cape     47.46
Free State       43.83
Gauteng          74.27
KwaZulu-Natal    90.34
Limpopo          41.85
Mpumalanga       38.39
North West       41.88
Northern Cape    14.74
Western Cape     55.75
Name: TotalClaims, dtype: float64

In [ ]:
from scipy import stats

# Separate claim amounts by province
eastern_cape_claims = df[df['Province'] == 'Eastern Cape']['TotalClaims']
free_state_claims = df[df['Province'] == 'Free State']['TotalClaims']
gauteng_claims = df[df['Province'] == 'Gauteng']['TotalClaims']
kwazulu_natal_claims = df[df['Province'] == 'KwaZulu-Natal']['TotalClaims']
limpopo_claims = df[df['Province'] == 'Limpopo']['TotalClaims']
mpumalanga_claims = df[df['Province'] == 'Mpumalanga']['TotalClaims']
north_west_claims = df[df['Province'] == 'North West']['TotalClaims']
northern_cape_claims = df[df['Province'] == 'Northern Cap']['TotalClaims']
western_cape_claims = df[df['Province'] == 'Western Cape']['TotalClaims']


# Perform the ANOVA test
f_stat, p_value_anova = stats.f_oneway(eastern_cape_claims, free_state_claims, gauteng_claims, kwazulu_natal_claims, limpopo_claims, mpumalanga_claims, north_west_claims, western_cape_claims)

print("--- ANOVA Results ---")
print(f"F-statistic: {f_stat:.4f}")
print(f"P-value: {p_value_anova:.4f}")
print(f"Alpha level: 0.05")
print()

# Interpret the result
if p_value_anova < 0.05:
    print("✅ Result: Reject the null hypothesis.")
    print("   There is a significant difference in total claims between provinces.")
else:
    print("❌ Result: Fail to reject the null hypothesis.")
    print("   No significant difference in total claims between provinces.")

print(f"\nDescriptive Statistics by Province:")
province_stats = df.groupby('Province')['TotalClaims'].agg(['mean', 'std', 'count']).round(2)
print(province_stats)

--- ANOVA Results ---
F-statistic: 7.1533
P-value: 0.0000
Alpha level: 0.05

✅ Result: Reject the null hypothesis.
   There is a significant difference in claim amounts between provinces.

Descriptive Statistics by Province:
                mean      std   count
Province
Eastern Cape   47.46  2416.39   28535
Free State     43.83  2074.60    8097
Gauteng        74.27  2414.17  375753
KwaZulu-Natal  90.34  2858.29  147306
Limpopo        41.85  1645.73   24291
Mpumalanga     38.39  1648.81   51528
North West     41.88  1847.57  141317
Northern Cape  14.74   533.25    5903
Western Cape   55.75  2405.97  166597

#### H₀:There are no risk differences between zip codes

In [13]:
# Get list of provinces
print(df.groupby('PostalCode')['TotalClaims'].mean().round(2))

PostalCode
1        60.72
2        41.59
4         0.00
5       207.38
6        19.61
         ...
9781    139.50
9830      0.00
9868      0.00
9869      1.58
9870      0.00
Name: TotalClaims, Length: 842, dtype: float64

In [ ]:
from scipy import stats
import pandas as pd

# Make sure PostalCode is treated as categorical
df['PostalCode'] = df['PostalCode'].astype(str)

# Group claims by postal code
groups = [group["TotalClaims"].values for _, group in df.groupby("PostalCode")]

# Perform the ANOVA test
f_stat, p_value_anova = stats.f_oneway(*groups)

print("--- ANOVA Results ---")
print(f"F-statistic: {f_stat:.4f}")
print(f"P-value: {p_value_anova:.4f}")
print(f"Alpha level: 0.05\n")

# Interpret the result
if p_value_anova < 0.05:
    print("✅ Result: Reject the null hypothesis.")
    print("   There is a significant difference in total claims between postal codes.")
else:
    print("❌ Result: Fail to reject the null hypothesis.")
    print("   No significant difference in total claims between postal codes.")

print("\nDescriptive Statistics by Postal Code:")
postal_stats = df.groupby("PostalCode")["TotalClaims"].agg(["mean", "std", "count"]).round(2)
print(postal_stats)

--- ANOVA Results ---
F-statistic: 1.0560
P-value: 0.1266
Alpha level: 0.05

❌ Result: Fail to reject the null hypothesis.
   No significant difference in claim amounts between postal codes.

Descriptive Statistics by Postal Code:
             mean      std  count
PostalCode
1           60.72  2171.46   5066
1000         0.00     0.00    320
1003         0.00     0.00    232
101          0.00     0.00    181
1020        67.46  2204.41   2554
...           ...      ...    ...
984          0.00     0.00    110
9868         0.00     0.00    100
9869         1.58    59.46   1415
9870         0.00     0.00    220
993          5.97   139.34    544

[842 rows x 3 columns]

#### H₀:There are no significant margin (profit) difference between zip codes

In [ ]:
from scipy import stats
import pandas as pd

# Make sure PostalCode is treated as categorical
df['PostalCode'] = df['PostalCode'].astype(str)

# Group claims by postal code
groups = [group["Margin"].values for _, group in df.groupby("PostalCode")]

# Perform the ANOVA test
f_stat, p_value_anova = stats.f_oneway(*groups)

print("--- ANOVA Results ---")
print(f"F-statistic: {f_stat:.4f}")
print(f"P-value: {p_value_anova:.4f}")
print(f"Alpha level: 0.05\n")

# Interpret the result
if p_value_anova < 0.05:
    print("✅ Result: Reject the null hypothesis.")
    print("   There is a significant difference in margin between postal codes.")
else:
    print("❌ Result: Fail to reject the null hypothesis.")
    print("   No significant difference in margin between postal codes.")

print("\nDescriptive Statistics by Postal Code:")
postal_stats = df.groupby("PostalCode")["Margin"].agg(["mean", "std", "count"]).round(2)
print(postal_stats)

--- ANOVA Results ---
F-statistic: 0.9522
P-value: 0.8364
Alpha level: 0.05

❌ Result: Fail to reject the null hypothesis.
   No significant difference in claim amounts between postal codes.

Descriptive Statistics by Postal Code:
              mean      std  count
PostalCode
1           -13.02  2162.73   5066
1000         45.51    98.02    320
1003         30.95    84.67    232
101         101.96   180.14    181
1020        -24.20  2193.44   2554
...            ...      ...    ...
984         104.08   193.26    110
9868        116.04   179.13    100
9869         43.19   132.31   1415
9870         80.47   129.92    220
993          15.02   156.92    544

[842 rows x 3 columns]

### Chi-Squared Test

#### - H₀:There are not significant risk difference between Women and Men

In [20]:
# Create a contingency table (crosstab)
contingency_table = pd.crosstab(df['Gender'], df['HasClaim'])
print("Contingency Table:")
print(contingency_table)
print()

# Perform the Chi-Squared test
chi2_stat, p_value_chi2, dof, expected = stats.chi2_contingency(contingency_table)

print("--- Chi-Squared Test Results ---")
print(f"Chi-Squared Statistic: {chi2_stat:.4f}")
print(f"P-value: {p_value_chi2:.4f}")
print(f"Degrees of Freedom: {dof}")
print(f"Alpha level: 0.05")
print()

# Interpret the result
if p_value_chi2 < 0.05:
    print("✅ Result: Reject the null hypothesis.")
    print("   There is a significant association between gender and having claims.")
else:
    print("❌ Result: Fail to reject the null hypothesis.")
    print("   There is no significant association between the variables.")

# Show the expected frequencies
print(f"\nExpected Frequencies:")
expected_df = pd.DataFrame(expected, 
                          index=contingency_table.index, 
                          columns=contingency_table.columns)
print(expected_df.round(2))

Contingency Table:
HasClaim            0     1
Gender
Female           6066    13
Male            42272    93
Not specified  898307  2576

--- Chi-Squared Test Results ---
Chi-Squared Statistic: 7.3604
P-value: 0.0252
Degrees of Freedom: 2
Alpha level: 0.05

✅ Result: Reject the null hypothesis.
   There is a significant association between gender and having claims.

Expected Frequencies:
HasClaim               0        1
Gender
Female           6061.83    17.17
Male            42245.31   119.69
Not specified  898337.86  2545.14